package domain;

public enum ProjectLocalization {
    AUVERGNE_RHONE_ALPES,
    BOURGOGNE_FRANCHE_COMPTE,
    BRETAGNE,
    CENTRE_VAL_DE_LOIRE,
    CORSE,
    GRAND_EST,
    HAUTS_DE_FRANCE,
    ILE_DE_FRANCE,
    NORMANDIE,
    NOUVELLE_ACQUITAINE,
    OCCITANIE,
    PAYS_DE_LA_LOIRE,
    PROVINCE_ALPES_COTE_D_AZUR
}
